<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Evenement extends \App\Entity\Evenement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'prix_even', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'desc_even', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'titre_even', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'nbre_place', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'date_debut', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'date_fin', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'idRes'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'prix_even', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'desc_even', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'titre_even', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'nbre_place', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'date_debut', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'date_fin', '' . "\0" . 'App\\Entity\\Evenement' . "\0" . 'idRes'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Evenement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixEven(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixEven', []);

        return parent::getPrixEven();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixEven(float $prix_even): \App\Entity\Evenement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixEven', [$prix_even]);

        return parent::setPrixEven($prix_even);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescEven(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescEven', []);

        return parent::getDescEven();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescEven(string $desc_even): \App\Entity\Evenement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescEven', [$desc_even]);

        return parent::setDescEven($desc_even);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitreEven(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitreEven', []);

        return parent::getTitreEven();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitreEven(string $titre_even): \App\Entity\Evenement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitreEven', [$titre_even]);

        return parent::setTitreEven($titre_even);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbrePlace(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbrePlace', []);

        return parent::getNbrePlace();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbrePlace(int $nbre_place): \App\Entity\Evenement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbrePlace', [$nbre_place]);

        return parent::setNbrePlace($nbre_place);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDebut(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDebut', []);

        return parent::getDateDebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDebut(\DateTimeInterface $date_debut): \App\Entity\Evenement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDebut', [$date_debut]);

        return parent::setDateDebut($date_debut);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFin(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFin', []);

        return parent::getDateFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFin(\DateTimeInterface $date_fin): \App\Entity\Evenement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFin', [$date_fin]);

        return parent::setDateFin($date_fin);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdRes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdRes', []);

        return parent::getIdRes();
    }

    /**
     * {@inheritDoc}
     */
    public function addIdRe(\App\Entity\Reservation $idRe): \App\Entity\Evenement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIdRe', [$idRe]);

        return parent::addIdRe($idRe);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIdRe(\App\Entity\Reservation $idRe): \App\Entity\Evenement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIdRe', [$idRe]);

        return parent::removeIdRe($idRe);
    }

}
