<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAFLeyv5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAFLeyv5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAFLeyv5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAFLeyv5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAFLeyv5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AFLeyv5',
    'container.build_id' => '599f73f9',
    'container.build_time' => 1645702515,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAFLeyv5');
