<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], [], []],
    'accueil' => [[], ['_controller' => 'App\\Controller\\AccueilController::index'], [], [['text', '/accueil']], [], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\AdminController::index'], [], [['text', '/admin']], [], [], []],
    'devis_index' => [[], ['_controller' => 'App\\Controller\\DevisController::index'], [], [['text', '/devis/']], [], [], []],
    'devis_new' => [[], ['_controller' => 'App\\Controller\\DevisController::new'], [], [['text', '/devis/new']], [], [], []],
    'devis_show' => [['id'], ['_controller' => 'App\\Controller\\DevisController::show'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/devis']], [], [], []],
    'devis_edit' => [['id'], ['_controller' => 'App\\Controller\\DevisController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id'], ['text', '/devis']], [], [], []],
    'devis_delete' => [['id'], ['_controller' => 'App\\Controller\\DevisController::delete'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/devis']], [], [], []],
    'reservation_cd_index' => [[], ['_controller' => 'App\\Controller\\ReservationCdController::index'], [], [['text', '/reservation/cd/']], [], [], []],
    'reservation_cd_indexback' => [[], ['_controller' => 'App\\Controller\\ReservationCdController::indexb'], [], [['text', '/reservation/cd/ind']], [], [], []],
    'devis_indexd' => [[], ['_controller' => 'App\\Controller\\ReservationCdController::devis'], [], [['text', '/reservation/cd/listedevis']], [], [], []],
    'evenchoisi' => [[], ['_controller' => 'App\\Controller\\ReservationCdController::indexf'], [], [['text', '/reservation/cd/evenchoisi']], [], [], []],
    'succes' => [[], ['_controller' => 'App\\Controller\\ReservationCdController::succes'], [], [['text', '/reservation/cd/succes']], [], [], []],
    'reservation_cd_new' => [[], ['_controller' => 'App\\Controller\\ReservationCdController::new'], [], [['text', '/reservation/cd/new']], [], [], []],
    'reservation_cd_show' => [['id'], ['_controller' => 'App\\Controller\\ReservationCdController::show'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/reservation/cd']], [], [], []],
    'reservation_cd_edit' => [['id'], ['_controller' => 'App\\Controller\\ReservationCdController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id'], ['text', '/reservation/cd']], [], [], []],
    'reservation_cd_delete' => [['id'], ['_controller' => 'App\\Controller\\ReservationCdController::delete'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/reservation/cd']], [], [], []],
];
